"""organiser model changed

Revision ID: 100e449086a6
Revises: bddaf3686d22
Create Date: 2021-09-19 11:28:15.915323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '100e449086a6'
down_revision = 'bddaf3686d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organiser', 'organiser_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organiser', sa.Column('organiser_name', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
