"""user email and phone number attribute changed

Revision ID: 9d1f74689a3d
Revises: ac7d7deddbf8
Create Date: 2021-10-16 21:56:04.869711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d1f74689a3d'
down_revision = 'ac7d7deddbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('life_users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('life_users', 'phone_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('life_users', 'phone_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('life_users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
