"""user_event_map added

Revision ID: bddaf3686d22
Revises: 24f320e386ab
Create Date: 2021-09-18 23:03:33.361660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddaf3686d22'
down_revision = '24f320e386ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event_map',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['life_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['life_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_event_map_created_at'), 'user_event_map', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_event_map_id'), 'user_event_map', ['id'], unique=False)
    op.create_index(op.f('ix_user_event_map_last_updated_at'), 'user_event_map', ['last_updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_event_map_last_updated_at'), table_name='user_event_map')
    op.drop_index(op.f('ix_user_event_map_id'), table_name='user_event_map')
    op.drop_index(op.f('ix_user_event_map_created_at'), table_name='user_event_map')
    op.drop_table('user_event_map')
    # ### end Alembic commands ###
