"""empty message

Revision ID: dfe1e98d2b64
Revises: 9d1f74689a3d
Create Date: 2021-10-17 00:11:58.828517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfe1e98d2b64'
down_revision = '9d1f74689a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('life_users', sa.Column('social_profile_data', sa.JSON(), nullable=False))
    op.add_column('organiser', sa.Column('organiser_name', sa.String(length=255), nullable=False))
    op.alter_column('organiser', 'phone_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.create_unique_constraint(None, 'organiser', ['organiser_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organiser', type_='unique')
    op.alter_column('organiser', 'phone_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.drop_column('organiser', 'organiser_name')
    op.drop_column('life_users', 'social_profile_data')
    # ### end Alembic commands ###
